apiVersion : v1
kind : Service
metadata : 
  name: app1-service
  namespace : assignment
spec : 
  type: LoadBalancer
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000