AWSTemplateFormatVersion: "2010-09-09"

Resources:
  GroceryAddLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GroceryAdd
      Handler: index.handler 
      Role: arn:aws:iam::579043522960:role/LabRole 
      Runtime: nodejs20.x  
      Timeout: 60  
      Code:
        S3Bucket: code-b00934576
        S3Key: grocery-add.zip  

  GroceryGetLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GroceryGet
      Handler: index.handler
      Role: arn:aws:iam::579043522960:role/LabRole
      Runtime: nodejs20.x
      Timeout: 60
      Code: 
        S3Bucket: code-b00934576
        S3Key: grocery-get.zip
grto
  GroceryEditLambda:
    Type: AWS::Lambda::Function
    Properties: 
      FunctionName: GroceryEdit
      Handler: index.handler
      Role: arn:aws:iam::579043522960:role/LabRole
      Runtime: nodejs20.x
      Timeout: 60
      Code: 
        S3Bucket: code-b00934576
        S3Key: grocery-edit.zip

  GroceryDeleteLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GroceryDelete
      Handler: index.handler
      Role: arn:aws:iam::579043522960:role/LabRole
      Runtime: nodejs20.x
      Timeout: 60
      code:
        S3Bucket: code-b00934576
        S3Key: grocery-delete.zip
