networks:
    my-network:
      driver: bridge

services:
  app1:
    image: otto335/cloud_computing:app1
    container_name: express-app1
    working_dir: /app
    ports:
      - "6000:6000"  
    networks:
      - my-network
    volumes:
      - .:/app/data
    command: npm start

  app2:
    image: otto335/cloud_computing:app2  # Replace with the actual image for your temperature service
    container_name: express-app2
    working_dir: /app
    ports:
      - "3000:3000"  # Map host port 5000 to container port 5000
    networks:
      - my-network
    volumes:
      - .:/app/data
    command: npm start

 